import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import HomePageLayout from "@/layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Live",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name='keyword' content='E-commerce'></meta>
      </head>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <HomePageLayout>{children}</HomePageLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
